### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by RadicalZephyr** [milesrout/sodium#1]
This name squatting that you're doing is pretty lame.

**Comment by milesrout** [comment]
There are two reasons I've done it.

Firstly I think that having a centralised squattable namespace is a terrible idea. I should not be able to reserve a name for years. But I can and so it's a bit of a protest.

Secondly, I do like Rust and do eventually plan to do things with the couple of names I reserved.

But y'know it's not like it's permanent. I transferred a name (can't remember what name now) to someone that asked nicely. If you'd sent me an email nicely asking for the name you'd probably have it by Thursday (I'm on holiday). As is, you won't.

Cheers,
Miles.

**Comment by RadicalZephyr** [comment]
I'm with you on the central squattable namespace being a bad idea. I disagree that this is any kind of meaningful protest, it just makes the squatting problem worse. And I don't actually want the name so you can keep squatting it.
